/**
 * Tower Report — /api/stories
 *
 * Serves the pre-generated AI stories archive from Vercel Blob.
 * Stories are generated by /api/stories-refresh (run via the
 * /api/daily-refresh cron orchestrator, twice daily) and accumulated
 * up to 60 stories, newest first. This endpoint is a fast Blob read —
 * no AI latency at page load time.
 *
 * Env vars:
 *   BLOB_READ_WRITE_TOKEN — Vercel Blob token
 */

export const config = { runtime: 'edge' };

const BLOB_PREFIX = 'tower-ai-stories'; // prefix without .json — REST API appends random hash to URL
const BLOB_API = 'https://blob.vercel-storage.com';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
};

export default async function handler(req) {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS });
  }

  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    return new Response(JSON.stringify({ error: 'Storage not configured', stories: [] }), {
      status: 503,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  try {
    const listUrl = `${BLOB_API}?prefix=${encodeURIComponent(BLOB_PREFIX)}&limit=10`;
    const listRes = await fetch(listUrl, {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!listRes.ok) {
      const errBody = await listRes.text().catch(() => '');
      console.error('[tower/stories] blob list error', listRes.status, errBody.slice(0, 200));
      throw new Error(`Blob list ${listRes.status}`);
    }

    const listData = await listRes.json();
    const blobs = listData.blobs || [];
    // Use the most recently uploaded blob (orphan cleanup happens in stories-refresh)
    blobs.sort((a, b) => new Date(b.uploadedAt) - new Date(a.uploadedAt));
    const blob = blobs[0];

    if (!blob) {
      return new Response(JSON.stringify({ stories: [], lastUpdated: null, _empty: true }), {
        status: 200,
        headers: { ...CORS, 'Content-Type': 'application/json' },
      });
    }

    // Fetch the stored stories
    const dataRes = await fetch(blob.downloadUrl || blob.url);
    if (!dataRes.ok) throw new Error(`Blob fetch ${dataRes.status}`);

    const stories = await dataRes.json();

    // lastUpdated must reflect the newest story's actual generation time
    let lastUpdated = null;
    for (const s of stories) {
      const t = s._generated || null;
      if (t && (!lastUpdated || t > lastUpdated)) lastUpdated = t;
    }

    return new Response(JSON.stringify({
      lastUpdated: lastUpdated || blob.uploadedAt || null,
      count: stories.length,
      stories,
    }), {
      headers: {
        ...CORS,
        'Content-Type': 'application/json',
        'Cache-Control': 's-maxage=300, stale-while-revalidate=600',
      },
    });

  } catch (err) {
    console.error('[tower/stories]', err.message);
    return new Response(JSON.stringify({ error: err.message, stories: [] }), {
      status: 500,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }
}
